### ISSUE TITLE
Delete the temp dir ... completely?

### ISSUE THREAD

**Issue by Dendraspis** [jessielw/DeeZy#36]
Just something to think about:

Basically there is no need to specify a temp dir. In my case I had not enough space left, so I have chosen an HDD and gladfully I have specified an empty folder, because this code look like: *When a temp dir is set, delete everything in it, even subfolders*.  😮 

So in case you set `--temp-dir="D:\"` and forget to add `--keep-temp` everything will be lost, right? 

https://github.com/jlw4049/DeeZy/blob/25224319d36b0f36fae98833fd40b2bd8ba2e782/deezy/audio_encoders/dee/dd.py#L181-L185

https://github.com/jlw4049/DeeZy/blob/25224319d36b0f36fae98833fd40b2bd8ba2e782/deezy/audio_encoders/dee/ddp.py#L176-L189

**Comment by jessielw** [comment]
I see `dd` is not properly deleting all files inside of the directory properly! However, both of them seems like they could be problematic. 

In this case a subfolder might be necessary to control things or another alternative. 

In it's current state, as long as no one supplied `--temp-dir` there would be no negative side effects (as long as they had space on their main storage). Looking at the code and you bringing this to my attention, supplying `--temp-dir` could potentially cause unwanted side effects/issues. 

I will look into this today!
