### ISSUE TITLE
Add Atmos Support 

### ISSUE THREAD

**Issue by jessielw** [jessielw/DeeZy#9]

**Comment by DRX-Lab** [comment]
The observations are appreciated. Regarding the use of **default=True** for the **-bc** parameter in **--bed-conform**, this was a test that was unintentionally left active, and therefore, it should be reverted to its original setting.

As for the values in DeeZy, it is recommended to adjust the **speech\_threshold** to 15, in line with Dolby’s guidelines. Additionally, both **drc** and **downmix mode** should be set to **"none"**, as these settings are crucial to ensure compatibility with Dolby’s best practices. While users have the freedom to select their preferred **drc** and **downmix** settings, these recommendations have been followed in the development of the **Atmos Encoder** to maintain compatibility with Dolby standards. The **downmix** option will be added in the next update.

It is recommended to review these settings in DeeZy, as they are more closely aligned with the official guidelines.

**Comment by jessielw** [comment]
- `speech_threshold` Looking at the documentation it appears that **20** is the default for all work flows. 
- `preferred_downmix_mode` Doesn't appear to have a "none" option. There are only **not_indicated, loro, ltrt, ltrt-pl2** and based on the profile it is either defaulted to **not_indicated** or **ltrt-pl2** per the docs. 
- `drc` Per the documentation for both line/rf modes defaults to **film_standard**. 

Do you have some other official documentation that isn't the DEE documentation where you are getting this information?

**Comment by jessielw** [comment]
Thanks I figured it out! I'm going to add the full DME capabilities to DeeZy over the next couple of days with the defaults set.
